# Generated by Django 3.2.9 on 2022-01-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0006_alter_profile_neighborhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='owner',
            new_name='user',
        ),
    ]
