# Generated by Django 3.2.9 on 2022-01-08 19:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0010_auto_20220108_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
