# Generated by Django 3.2.9 on 2022-01-08 19:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0011_alter_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorities',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
