# Generated by Django 3.2.9 on 2022-01-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0013_health_healthservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='healthservices',
        ),
        migrations.DeleteModel(
            name='healthservices',
        ),
    ]
