# Generated by Django 3.2.9 on 2022-01-08 21:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0014_auto_20220109_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
